# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a09c1fec623c56a6ed5e6bc615d3fedb1c78a144f3b2a2130bd5fab5f7207666e481b0fe9ee0147c11d188068b1945d1cf767a8a646f1f75fe420d615ccfef4

test:
  secret_key_base: caea4476a5d60c6896e71487683cd9fe8cb0fb6ae529344de41ea33a100f4c01be55159ba68cc2cf4d599007c0fd6eab1dfc195add5838f8289dd67e6fda7da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
